# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcospb19/projeto-itp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcospb19/projeto-itp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcospb19/projeto-itp/CMakeFiles /home/marcospb19/projeto-itp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcospb19/projeto-itp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sgbd

# Build rule for target.
sgbd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sgbd
.PHONY : sgbd

# fast build rule for target.
sgbd/fast:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/build
.PHONY : sgbd/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.s
.PHONY : main.c.s

source/colors.o: source/colors.c.o

.PHONY : source/colors.o

# target to build an object file
source/colors.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/colors.c.o
.PHONY : source/colors.c.o

source/colors.i: source/colors.c.i

.PHONY : source/colors.i

# target to preprocess a source file
source/colors.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/colors.c.i
.PHONY : source/colors.c.i

source/colors.s: source/colors.c.s

.PHONY : source/colors.s

# target to generate assembly for a file
source/colors.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/colors.c.s
.PHONY : source/colors.c.s

source/command.o: source/command.c.o

.PHONY : source/command.o

# target to build an object file
source/command.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/command.c.o
.PHONY : source/command.c.o

source/command.i: source/command.c.i

.PHONY : source/command.i

# target to preprocess a source file
source/command.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/command.c.i
.PHONY : source/command.c.i

source/command.s: source/command.c.s

.PHONY : source/command.s

# target to generate assembly for a file
source/command.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/command.c.s
.PHONY : source/command.c.s

source/list.o: source/list.c.o

.PHONY : source/list.o

# target to build an object file
source/list.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/list.c.o
.PHONY : source/list.c.o

source/list.i: source/list.c.i

.PHONY : source/list.i

# target to preprocess a source file
source/list.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/list.c.i
.PHONY : source/list.c.i

source/list.s: source/list.c.s

.PHONY : source/list.s

# target to generate assembly for a file
source/list.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/list.c.s
.PHONY : source/list.c.s

source/messages.o: source/messages.c.o

.PHONY : source/messages.o

# target to build an object file
source/messages.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/messages.c.o
.PHONY : source/messages.c.o

source/messages.i: source/messages.c.i

.PHONY : source/messages.i

# target to preprocess a source file
source/messages.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/messages.c.i
.PHONY : source/messages.c.i

source/messages.s: source/messages.c.s

.PHONY : source/messages.s

# target to generate assembly for a file
source/messages.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/messages.c.s
.PHONY : source/messages.c.s

source/struct.o: source/struct.c.o

.PHONY : source/struct.o

# target to build an object file
source/struct.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/struct.c.o
.PHONY : source/struct.c.o

source/struct.i: source/struct.c.i

.PHONY : source/struct.i

# target to preprocess a source file
source/struct.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/struct.c.i
.PHONY : source/struct.c.i

source/struct.s: source/struct.c.s

.PHONY : source/struct.s

# target to generate assembly for a file
source/struct.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/struct.c.s
.PHONY : source/struct.c.s

source/tables.o: source/tables.c.o

.PHONY : source/tables.o

# target to build an object file
source/tables.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/tables.c.o
.PHONY : source/tables.c.o

source/tables.i: source/tables.c.i

.PHONY : source/tables.i

# target to preprocess a source file
source/tables.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/tables.c.i
.PHONY : source/tables.c.i

source/tables.s: source/tables.c.s

.PHONY : source/tables.s

# target to generate assembly for a file
source/tables.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/source/tables.c.s
.PHONY : source/tables.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sgbd"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/colors.o"
	@echo "... source/colors.i"
	@echo "... source/colors.s"
	@echo "... source/command.o"
	@echo "... source/command.i"
	@echo "... source/command.s"
	@echo "... source/list.o"
	@echo "... source/list.i"
	@echo "... source/list.s"
	@echo "... source/messages.o"
	@echo "... source/messages.i"
	@echo "... source/messages.s"
	@echo "... source/struct.o"
	@echo "... source/struct.i"
	@echo "... source/struct.s"
	@echo "... source/tables.o"
	@echo "... source/tables.i"
	@echo "... source/tables.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

