# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcospb19/projeto-itp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcospb19/projeto-itp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcospb19/projeto-itp/CMakeFiles /home/marcospb19/projeto-itp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcospb19/projeto-itp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sgbd

# Build rule for target.
sgbd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sgbd
.PHONY : sgbd

# fast build rule for target.
sgbd/fast:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/build
.PHONY : sgbd/fast

libraries/colors.o: libraries/colors.c.o

.PHONY : libraries/colors.o

# target to build an object file
libraries/colors.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/colors.c.o
.PHONY : libraries/colors.c.o

libraries/colors.i: libraries/colors.c.i

.PHONY : libraries/colors.i

# target to preprocess a source file
libraries/colors.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/colors.c.i
.PHONY : libraries/colors.c.i

libraries/colors.s: libraries/colors.c.s

.PHONY : libraries/colors.s

# target to generate assembly for a file
libraries/colors.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/colors.c.s
.PHONY : libraries/colors.c.s

libraries/command.o: libraries/command.c.o

.PHONY : libraries/command.o

# target to build an object file
libraries/command.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/command.c.o
.PHONY : libraries/command.c.o

libraries/command.i: libraries/command.c.i

.PHONY : libraries/command.i

# target to preprocess a source file
libraries/command.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/command.c.i
.PHONY : libraries/command.c.i

libraries/command.s: libraries/command.c.s

.PHONY : libraries/command.s

# target to generate assembly for a file
libraries/command.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/command.c.s
.PHONY : libraries/command.c.s

libraries/list.o: libraries/list.c.o

.PHONY : libraries/list.o

# target to build an object file
libraries/list.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/list.c.o
.PHONY : libraries/list.c.o

libraries/list.i: libraries/list.c.i

.PHONY : libraries/list.i

# target to preprocess a source file
libraries/list.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/list.c.i
.PHONY : libraries/list.c.i

libraries/list.s: libraries/list.c.s

.PHONY : libraries/list.s

# target to generate assembly for a file
libraries/list.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/list.c.s
.PHONY : libraries/list.c.s

libraries/messages.o: libraries/messages.c.o

.PHONY : libraries/messages.o

# target to build an object file
libraries/messages.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/messages.c.o
.PHONY : libraries/messages.c.o

libraries/messages.i: libraries/messages.c.i

.PHONY : libraries/messages.i

# target to preprocess a source file
libraries/messages.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/messages.c.i
.PHONY : libraries/messages.c.i

libraries/messages.s: libraries/messages.c.s

.PHONY : libraries/messages.s

# target to generate assembly for a file
libraries/messages.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/messages.c.s
.PHONY : libraries/messages.c.s

libraries/struct.o: libraries/struct.c.o

.PHONY : libraries/struct.o

# target to build an object file
libraries/struct.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/struct.c.o
.PHONY : libraries/struct.c.o

libraries/struct.i: libraries/struct.c.i

.PHONY : libraries/struct.i

# target to preprocess a source file
libraries/struct.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/struct.c.i
.PHONY : libraries/struct.c.i

libraries/struct.s: libraries/struct.c.s

.PHONY : libraries/struct.s

# target to generate assembly for a file
libraries/struct.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/struct.c.s
.PHONY : libraries/struct.c.s

libraries/tables.o: libraries/tables.c.o

.PHONY : libraries/tables.o

# target to build an object file
libraries/tables.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/tables.c.o
.PHONY : libraries/tables.c.o

libraries/tables.i: libraries/tables.c.i

.PHONY : libraries/tables.i

# target to preprocess a source file
libraries/tables.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/tables.c.i
.PHONY : libraries/tables.c.i

libraries/tables.s: libraries/tables.c.s

.PHONY : libraries/tables.s

# target to generate assembly for a file
libraries/tables.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/libraries/tables.c.s
.PHONY : libraries/tables.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/sgbd.dir/build.make CMakeFiles/sgbd.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sgbd"
	@echo "... edit_cache"
	@echo "... libraries/colors.o"
	@echo "... libraries/colors.i"
	@echo "... libraries/colors.s"
	@echo "... libraries/command.o"
	@echo "... libraries/command.i"
	@echo "... libraries/command.s"
	@echo "... libraries/list.o"
	@echo "... libraries/list.i"
	@echo "... libraries/list.s"
	@echo "... libraries/messages.o"
	@echo "... libraries/messages.i"
	@echo "... libraries/messages.s"
	@echo "... libraries/struct.o"
	@echo "... libraries/struct.i"
	@echo "... libraries/struct.s"
	@echo "... libraries/tables.o"
	@echo "... libraries/tables.i"
	@echo "... libraries/tables.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

